# -*- coding: utf-8 -*-
"""road_data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RTihp3cM46xVT5sfIkfw9Bx8UN4H0h4D
"""

#한글 폰트 설치

!apt-get update -qq
!apt-get install fonts-nanum* -qq

# 기본글꼴 변경
import matplotlib as mp
#mp.font_manager._rebuild()
mp.pyplot.rc('font', family='NanumGothic')

#코랩 한글 깨짐 현상 해결 방법

!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

from google.colab import files
road_file = files.upload()

import io
import pandas as pd

data = pd.read_csv(io.BytesIO(road_file['road_data.csv']))
data.head()

import pandas as pd
import matplotlib.pylab as plt

fig = plt.figure(figsize=(14,6))
plt.bar(data['발생년'],data['사고건수']) 


ax = plt.subplot(1,1,1)

ax.set_ylabel('사고건수',fontweight='bold', fontsize = 12)
ax.set_xlabel('발생년',fontweight='bold', fontsize = 12)
ax.set_title('도로교통공단_2017~2021 교통사고 통계',fontweight='bold', fontsize = 12)

data.to_excel("output.xlsx", index=False)